// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBiJtIAtWdXmu7cM64q609Z6S6ZefCCLGw',
    appId: '1:35400043805:web:651a3b214ee2dee10de5f4',
    messagingSenderId: '35400043805',
    projectId: 'delivery-courier-app-2983b',
    authDomain: 'delivery-courier-app-2983b.firebaseapp.com',
    storageBucket: 'delivery-courier-app-2983b.firebasestorage.app',
    measurementId: 'G-9F7ESB7ZWN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEI0Z_-bSQg7NYKQfspHP8a4QSJN54vPQ',
    appId: '1:35400043805:android:3f118f2f5f17507c0de5f4',
    messagingSenderId: '35400043805',
    projectId: 'delivery-courier-app-2983b',
    storageBucket: 'delivery-courier-app-2983b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0TIZWboMGVPNieA3ZH49lqvH6PIurrEg',
    appId: '1:35400043805:ios:022af3f4f9112aa40de5f4',
    messagingSenderId: '35400043805',
    projectId: 'delivery-courier-app-2983b',
    storageBucket: 'delivery-courier-app-2983b.firebasestorage.app',
    iosBundleId: 'com.example.deliveryCourierApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB0TIZWboMGVPNieA3ZH49lqvH6PIurrEg',
    appId: '1:35400043805:ios:022af3f4f9112aa40de5f4',
    messagingSenderId: '35400043805',
    projectId: 'delivery-courier-app-2983b',
    storageBucket: 'delivery-courier-app-2983b.firebasestorage.app',
    iosBundleId: 'com.example.deliveryCourierApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBiJtIAtWdXmu7cM64q609Z6S6ZefCCLGw',
    appId: '1:35400043805:web:a0a138eb758111520de5f4',
    messagingSenderId: '35400043805',
    projectId: 'delivery-courier-app-2983b',
    authDomain: 'delivery-courier-app-2983b.firebaseapp.com',
    storageBucket: 'delivery-courier-app-2983b.firebasestorage.app',
    measurementId: 'G-5WENH292RB',
  );
}
